---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: go-app-http-scaled-object
  namespace: kubenet
  annotations:
    httpscaledobject.keda.sh/skip-scaledobject-creation: "true"
spec:
  hosts:
    - go-service.kubenet.svc.cluster.local
  replicas:
    max: 3
    min: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
    port: 4000
    service: go-service