apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-service
  name: go-service
  namespace: kubenet
spec:
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: 8082
  selector:
    app: app-deployment
  type: ClusterIP
status:
  loadBalancer: {}